export interface LogEntry {
  status: "pending" | "approved" | "denied" | "cancelled";
  date: Date;
  approvedBy?: string;
  reason?: string;
}

export interface AdjustmentRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  position: string;
  department: string;
  shiftDateFrom: Date;
  shiftDateTo: Date;
  clockInTime: string;
  clockOutTime: string;
  reason: "Forgot to Clock-in/Clock-out" | "Missing logs";
  breakDuration: number;
  message: string;
  status: "approved" | "denied" | "pending" | "cancelled";
  submittedDate: Date;
  attachments: string[];
  logTrail: LogEntry[];
}

export const getInitialAdjustmentRequests = (): AdjustmentRequest[] => [
  // Pending requests (5)
  {
    id: "adj-001",
    employeeId: "emp-2",
    employeeName: "John Smith",
    position: "Senior Developer",
    department: "Engineering",
    shiftDateFrom: new Date(2025, 9, 21),
    shiftDateTo: new Date(2025, 9, 21),
    clockInTime: "9:30 AM",
    clockOutTime: "6:15 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "I forgot to clock in this morning as I went straight into a meeting. My actual arrival time was around 9:30 AM based on building security logs.",
    status: "pending",
    submittedDate: new Date(2025, 9, 22),
    attachments: ["security-log.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 22) },
    ],
  },
  {
    id: "adj-002",
    employeeId: "emp-7",
    employeeName: "Lisa Anderson",
    position: "Support Agent",
    department: "Customer Support",
    shiftDateFrom: new Date(2025, 9, 23),
    shiftDateTo: new Date(2025, 9, 23),
    clockInTime: "8:45 AM",
    clockOutTime: "5:30 PM",
    reason: "Missing logs",
    breakDuration: 45,
    message: "System error occurred and my attendance was not recorded. I have emails timestamped showing I was working during this period.",
    status: "pending",
    submittedDate: new Date(2025, 9, 24),
    attachments: ["email-screenshot.png", "system-error-report.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 24) },
    ],
  },
  {
    id: "adj-003",
    employeeId: "emp-4",
    employeeName: "Jennifer Lee",
    position: "Marketing Manager",
    department: "Marketing",
    shiftDateFrom: new Date(2025, 9, 20),
    shiftDateTo: new Date(2025, 9, 20),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Had an emergency client call and rushed into the office forgetting to clock in. Can verify with calendar invite.",
    status: "pending",
    submittedDate: new Date(2025, 9, 21),
    attachments: ["calendar-invite.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 21) },
    ],
  },
  {
    id: "adj-004",
    employeeId: "emp-9",
    employeeName: "Daniel Thompson",
    position: "Product Manager",
    department: "Product",
    shiftDateFrom: new Date(2025, 9, 22),
    shiftDateTo: new Date(2025, 9, 22),
    clockInTime: "8:30 AM",
    clockOutTime: "5:45 PM",
    reason: "Missing logs",
    breakDuration: 30,
    message: "Card reader malfunction prevented me from clocking in/out. Security desk can confirm my entry and exit times.",
    status: "pending",
    submittedDate: new Date(2025, 9, 23),
    attachments: ["security-confirmation.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 23) },
    ],
  },
  {
    id: "adj-005",
    employeeId: "emp-11",
    employeeName: "Christopher Davis",
    position: "Sales Representative",
    department: "Sales",
    shiftDateFrom: new Date(2025, 9, 24),
    shiftDateTo: new Date(2025, 9, 24),
    clockInTime: "9:15 AM",
    clockOutTime: "6:30 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 45,
    message: "Was attending a client meeting offsite in the morning and forgot to clock in when I arrived at the office afterward.",
    status: "pending",
    submittedDate: new Date(2025, 9, 25),
    attachments: ["client-meeting-notes.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 25) },
    ],
  },
  // Approved requests (5)
  {
    id: "adj-006",
    employeeId: "emp-3",
    employeeName: "James Wilson",
    position: "Senior Developer",
    department: "Engineering",
    shiftDateFrom: new Date(2025, 9, 15),
    shiftDateTo: new Date(2025, 9, 15),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "System glitch prevented clock-in. Verified by IT department.",
    status: "approved",
    submittedDate: new Date(2025, 9, 16),
    attachments: ["it-ticket.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 16) },
      { status: "approved", date: new Date(2025, 9, 17), approvedBy: "Sarah Martinez" },
    ],
  },
  {
    id: "adj-007",
    employeeId: "emp-6",
    employeeName: "Karen Brown",
    position: "Operations Coordinator",
    department: "Operations",
    shiftDateFrom: new Date(2025, 9, 14),
    shiftDateTo: new Date(2025, 9, 14),
    clockInTime: "8:45 AM",
    clockOutTime: "5:30 PM",
    reason: "Missing logs",
    breakDuration: 45,
    message: "Power outage caused system to lose my attendance record.",
    status: "approved",
    submittedDate: new Date(2025, 9, 15),
    attachments: ["power-outage-notice.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 15) },
      { status: "approved", date: new Date(2025, 9, 16), approvedBy: "Michael Chen" },
    ],
  },
  {
    id: "adj-008",
    employeeId: "emp-8",
    employeeName: "Emily Rodriguez",
    position: "UI/UX Designer",
    department: "Design",
    shiftDateFrom: new Date(2025, 9, 13),
    shiftDateTo: new Date(2025, 9, 13),
    clockInTime: "9:00 AM",
    clockOutTime: "6:15 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Started working remotely in the morning and forgot to clock in when I came to office for afternoon meetings.",
    status: "approved",
    submittedDate: new Date(2025, 9, 14),
    attachments: ["meeting-schedule.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 14) },
      { status: "approved", date: new Date(2025, 9, 15), approvedBy: "Sarah Martinez" },
    ],
  },
  {
    id: "adj-009",
    employeeId: "emp-10",
    employeeName: "Robert Martinez",
    position: "Product Manager",
    department: "Product",
    shiftDateFrom: new Date(2025, 9, 10),
    shiftDateTo: new Date(2025, 9, 10),
    clockInTime: "8:30 AM",
    clockOutTime: "5:45 PM",
    reason: "Missing logs",
    breakDuration: 30,
    message: "Attendance kiosk was offline. Multiple employees affected.",
    status: "approved",
    submittedDate: new Date(2025, 9, 11),
    attachments: ["kiosk-maintenance-report.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 11) },
      { status: "approved", date: new Date(2025, 9, 12), approvedBy: "Michael Chen" },
    ],
  },
  {
    id: "adj-010",
    employeeId: "emp-12",
    employeeName: "David Kim",
    position: "Sales Representative",
    department: "Sales",
    shiftDateFrom: new Date(2025, 9, 9),
    shiftDateTo: new Date(2025, 9, 9),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock out due to urgent client emergency.",
    status: "approved",
    submittedDate: new Date(2025, 9, 10),
    attachments: ["client-emergency-email.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 10) },
      { status: "approved", date: new Date(2025, 9, 11), approvedBy: "Sarah Martinez" },
    ],
  },
  // Denied requests (5)
  {
    id: "adj-011",
    employeeId: "emp-1",
    employeeName: "Sarah Johnson",
    position: "Marketing Manager",
    department: "Marketing",
    shiftDateFrom: new Date(2025, 9, 7),
    shiftDateTo: new Date(2025, 9, 7),
    clockInTime: "10:00 AM",
    clockOutTime: "7:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock in.",
    status: "denied",
    submittedDate: new Date(2025, 9, 8),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 8) },
      { status: "denied", date: new Date(2025, 9, 9), approvedBy: "Michael Chen", reason: "No supporting documentation provided. Please provide evidence of your actual work hours." },
    ],
  },
  {
    id: "adj-012",
    employeeId: "emp-5",
    employeeName: "Michael Chen",
    position: "Financial Analyst",
    department: "Finance",
    shiftDateFrom: new Date(2025, 9, 6),
    shiftDateTo: new Date(2025, 9, 6),
    clockInTime: "11:00 AM",
    clockOutTime: "8:00 PM",
    reason: "Missing logs",
    breakDuration: 60,
    message: "System error.",
    status: "denied",
    submittedDate: new Date(2025, 9, 7),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 7) },
      { status: "denied", date: new Date(2025, 9, 8), approvedBy: "Sarah Martinez", reason: "IT department confirmed no system errors on this date. Please provide accurate information." },
    ],
  },
  {
    id: "adj-013",
    employeeId: "emp-13",
    employeeName: "Amanda White",
    position: "HR Specialist",
    department: "HR",
    shiftDateFrom: new Date(2025, 9, 3),
    shiftDateTo: new Date(2025, 9, 3),
    clockInTime: "10:30 AM",
    clockOutTime: "7:30 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Was late and forgot to clock in.",
    status: "denied",
    submittedDate: new Date(2025, 9, 4),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 4) },
      { status: "denied", date: new Date(2025, 9, 5), approvedBy: "Michael Chen", reason: "Late arrival without prior approval. Attendance policy requires prior notification for late arrivals." },
    ],
  },
  {
    id: "adj-014",
    employeeId: "emp-14",
    employeeName: "Brian Wilson",
    position: "Data Analyst",
    department: "Analytics",
    shiftDateFrom: new Date(2025, 8, 30),
    shiftDateTo: new Date(2025, 8, 30),
    clockInTime: "9:30 AM",
    clockOutTime: "6:30 PM",
    reason: "Missing logs",
    breakDuration: 60,
    message: "I think there was a system issue.",
    status: "denied",
    submittedDate: new Date(2025, 9, 1),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 1) },
      { status: "denied", date: new Date(2025, 9, 2), approvedBy: "Sarah Martinez", reason: "Request submitted too late. Adjustment requests must be made within 24 hours of the occurrence." },
    ],
  },
  {
    id: "adj-015",
    employeeId: "emp-15",
    employeeName: "Jessica Taylor",
    position: "HR Specialist",
    department: "HR",
    shiftDateFrom: new Date(2025, 8, 28),
    shiftDateTo: new Date(2025, 8, 28),
    clockInTime: "10:00 AM",
    clockOutTime: "7:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock in yesterday.",
    status: "denied",
    submittedDate: new Date(2025, 8, 29),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 8, 29) },
      { status: "denied", date: new Date(2025, 8, 30), approvedBy: "Michael Chen", reason: "Security logs show arrival at 10:15 AM, not 10:00 AM as claimed. Please verify accurate times." },
    ],
  },
  // July 2026 pending requests (5)
  {
    id: "adj-jul-001",
    employeeId: "emp-3",
    employeeName: "James Wilson",
    position: "Senior Developer",
    department: "Engineering",
    shiftDateFrom: new Date(2026, 6, 18),
    shiftDateTo: new Date(2026, 6, 18),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "I went straight to a client demo in the morning and forgot to clock in. I arrived at the office at 9:00 AM after the demo.",
    status: "pending",
    submittedDate: new Date(2026, 6, 18),
    attachments: ["client-demo-invite.pdf"],
    logTrail: [{ status: "pending", date: new Date(2026, 6, 18) }],
  },
  {
    id: "adj-jul-002",
    employeeId: "emp-6",
    employeeName: "Karen Brown",
    position: "Operations Coordinator",
    department: "Operations",
    shiftDateFrom: new Date(2026, 6, 16),
    shiftDateTo: new Date(2026, 6, 16),
    clockInTime: "8:45 AM",
    clockOutTime: "5:30 PM",
    reason: "Missing logs",
    breakDuration: 45,
    message: "The attendance kiosk near our floor was offline for maintenance. IT can confirm the downtime window.",
    status: "pending",
    submittedDate: new Date(2026, 6, 17),
    attachments: ["it-maintenance-notice.pdf"],
    logTrail: [{ status: "pending", date: new Date(2026, 6, 17) }],
  },
  {
    id: "adj-jul-003",
    employeeId: "emp-9",
    employeeName: "Daniel Thompson",
    position: "Product Manager",
    department: "Product",
    shiftDateFrom: new Date(2026, 6, 14),
    shiftDateTo: new Date(2026, 6, 14),
    clockInTime: "8:30 AM",
    clockOutTime: "5:45 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 30,
    message: "Had an all-hands meeting immediately at 8:30 AM and forgot to clock in beforehand. Calendar invite attached as proof.",
    status: "pending",
    submittedDate: new Date(2026, 6, 15),
    attachments: ["all-hands-calendar.pdf"],
    logTrail: [{ status: "pending", date: new Date(2026, 6, 15) }],
  },
  {
    id: "adj-jul-004",
    employeeId: "emp-14",
    employeeName: "Brian Wilson",
    position: "Data Analyst",
    department: "Analytics",
    shiftDateFrom: new Date(2026, 6, 10),
    shiftDateTo: new Date(2026, 6, 10),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Missing logs",
    breakDuration: 60,
    message: "System recorded duplicate entries and my actual clock-in was removed during the cleanup. IT ticket submitted.",
    status: "pending",
    submittedDate: new Date(2026, 6, 11),
    attachments: ["it-ticket-1234.pdf"],
    logTrail: [{ status: "pending", date: new Date(2026, 6, 11) }],
  },
  {
    id: "adj-jul-005",
    employeeId: "emp-21",
    employeeName: "Olivia Nguyen",
    position: "HR Specialist",
    department: "HR",
    shiftDateFrom: new Date(2026, 6, 8),
    shiftDateTo: new Date(2026, 6, 8),
    clockInTime: "8:55 AM",
    clockOutTime: "5:55 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock out as I left during a fire drill and got caught up afterwards.",
    status: "pending",
    submittedDate: new Date(2026, 6, 9),
    attachments: ["fire-drill-notice.pdf"],
    logTrail: [{ status: "pending", date: new Date(2026, 6, 9) }],
  },
  // June 2026 approved requests (3)
  {
    id: "adj-jun-001",
    employeeId: "emp-4",
    employeeName: "Jennifer Lee",
    position: "Marketing Manager",
    department: "Marketing",
    shiftDateFrom: new Date(2026, 5, 25),
    shiftDateTo: new Date(2026, 5, 25),
    clockInTime: "9:00 AM",
    clockOutTime: "6:15 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Attended an offsite client workshop in the morning. Arrived at office at 9:00 AM after the workshop ended.",
    status: "approved",
    submittedDate: new Date(2026, 5, 26),
    attachments: ["workshop-agenda.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2026, 5, 26) },
      { status: "approved", date: new Date(2026, 5, 27), approvedBy: "Sarah Martinez" },
    ],
  },
  {
    id: "adj-jun-002",
    employeeId: "emp-7",
    employeeName: "Lisa Anderson",
    position: "Support Agent",
    department: "Customer Support",
    shiftDateFrom: new Date(2026, 5, 18),
    shiftDateTo: new Date(2026, 5, 18),
    clockInTime: "8:45 AM",
    clockOutTime: "5:30 PM",
    reason: "Missing logs",
    breakDuration: 45,
    message: "System crash during the morning shift caused records to be lost. Network logs confirm I was active on internal tools.",
    status: "approved",
    submittedDate: new Date(2026, 5, 19),
    attachments: ["network-activity-log.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2026, 5, 19) },
      { status: "approved", date: new Date(2026, 5, 20), approvedBy: "Michael Chen" },
    ],
  },
  {
    id: "adj-jun-003",
    employeeId: "emp-12",
    employeeName: "David Kim",
    position: "Sales Representative",
    department: "Sales",
    shiftDateFrom: new Date(2026, 5, 10),
    shiftDateTo: new Date(2026, 5, 10),
    clockInTime: "8:30 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Was on a sales call at 8:30 AM and clocked in from my phone, but the mobile sync failed.",
    status: "approved",
    submittedDate: new Date(2026, 5, 11),
    attachments: ["call-log.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2026, 5, 11) },
      { status: "approved", date: new Date(2026, 5, 12), approvedBy: "Sarah Martinez" },
    ],
  },
  // Cancelled requests (5)
  {
    id: "adj-016",
    employeeId: "emp-16",
    employeeName: "Nicole Adams",
    position: "Graphic Designer",
    department: "Design",
    shiftDateFrom: new Date(2025, 9, 5),
    shiftDateTo: new Date(2025, 9, 5),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock in this morning.",
    status: "cancelled",
    submittedDate: new Date(2025, 9, 6),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 6) },
      { status: "cancelled", date: new Date(2025, 9, 7), reason: "Found original clock-in record - adjustment not needed" },
    ],
  },
  {
    id: "adj-017",
    employeeId: "emp-17",
    employeeName: "Thomas Garcia",
    position: "DevOps Engineer",
    department: "Engineering",
    shiftDateFrom: new Date(2025, 9, 4),
    shiftDateTo: new Date(2025, 9, 4),
    clockInTime: "8:45 AM",
    clockOutTime: "5:45 PM",
    reason: "Missing logs",
    breakDuration: 45,
    message: "System didn't record my attendance.",
    status: "cancelled",
    submittedDate: new Date(2025, 9, 5),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 9, 5) },
      { status: "approved", date: new Date(2025, 9, 6), approvedBy: "Sarah Martinez" },
      { status: "cancelled", date: new Date(2025, 9, 7), reason: "Duplicate request - already processed under different ticket" },
    ],
  },
  {
    id: "adj-018",
    employeeId: "emp-18",
    employeeName: "Rachel Moore",
    position: "Content Writer",
    department: "Marketing",
    shiftDateFrom: new Date(2025, 8, 25),
    shiftDateTo: new Date(2025, 8, 25),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock out.",
    status: "cancelled",
    submittedDate: new Date(2025, 8, 26),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 8, 26) },
      { status: "cancelled", date: new Date(2025, 8, 27), reason: "Employee withdrew request - times were incorrect" },
    ],
  },
  {
    id: "adj-019",
    employeeId: "emp-19",
    employeeName: "Kevin Wright",
    position: "QA Engineer",
    department: "Engineering",
    shiftDateFrom: new Date(2025, 8, 23),
    shiftDateTo: new Date(2025, 8, 23),
    clockInTime: "9:00 AM",
    clockOutTime: "6:00 PM",
    reason: "Missing logs",
    breakDuration: 60,
    message: "Card reader issue.",
    status: "cancelled",
    submittedDate: new Date(2025, 8, 24),
    attachments: ["card-issue.pdf"],
    logTrail: [
      { status: "pending", date: new Date(2025, 8, 24) },
      { status: "approved", date: new Date(2025, 8, 25), approvedBy: "Michael Chen" },
      { status: "cancelled", date: new Date(2025, 8, 26), reason: "IT resolved the issue and recovered the original records" },
    ],
  },
  {
    id: "adj-020",
    employeeId: "emp-20",
    employeeName: "Samantha Hill",
    position: "Business Analyst",
    department: "Analytics",
    shiftDateFrom: new Date(2025, 8, 20),
    shiftDateTo: new Date(2025, 8, 20),
    clockInTime: "9:15 AM",
    clockOutTime: "6:15 PM",
    reason: "Forgot to Clock-in/Clock-out",
    breakDuration: 60,
    message: "Forgot to clock in due to early morning meeting.",
    status: "cancelled",
    submittedDate: new Date(2025, 8, 21),
    attachments: [],
    logTrail: [
      { status: "pending", date: new Date(2025, 8, 21) },
      { status: "cancelled", date: new Date(2025, 8, 22), reason: "Request no longer needed - manager updated timesheet directly" },
    ],
  },
];
