TRUNCATE TABLE
  app.attendance_leave_attachments,
  app.attendance_leave_details,
  app.attendance_records,
  app.adjustment_request_logs,
  app.adjustment_request_attachments,
  app.attendance_adjustment_requests,
  app.leave_request_logs,
  app.leave_request_attachments,
  app.leave_requests,
  app.leave_balances,
  app.leave_types,
  app.payroll_deductions,
  app.payroll_profiles,
  app.holidays,
  app.user_working_days,
  app.user_preferences,
  app_auth.password_activities,
  app_auth.login_attempts,
  app_auth.sessions,
  app_auth.user_roles,
  app_auth.users,
  app_auth.roles,
  app.employees,
  app.departments
RESTART IDENTITY CASCADE;

